# Dockerfile.python
FROM python:3.9 AS python-app
WORKDIR /usr/src/python-app
COPY ./python-app/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY ./python-app .
CMD ["python", "main.py"]